In [4]:
import numpy as np
from tqdm import tqdm_notebook

In [23]:
class sigmoidNeuron:
    
    def __init__(self):
        self.w = None
        self.b = None
        
    def model(self,x):
        return np.dot(x,self.w.T) + self.b
    
    def sigmoid(self,x):
        return 1.0/(1.0 + np.exp(x))
    
    def grad_w(self,x,y):
        y_pred = self.sigmoid(self.model(x))
        return (y_pred - y)*y_pred*(1 - y_pred)*x
    
    def grad_b(self,x,y):
        y_pred = self.sigmoid(self.model(x))
        return (y_pred - y)*y_pred*(1 - y_pred)
    
    def predict(X):
        Y_pred = []
        for x in X:
            y_pred = self.sigmoid(self.model(x))
            Y_pred.append(y_pred)
        return np.array(Y_pred)
    
    def fit(self,X,Y,epochs = 1,eta = 1,intialize = True):
        
        # Intialize w,b
        if intialize:
            self.w = np.random.randn(1,X.shape[1])
            self.b = 0
        
        for i in tqdm_notebook(range(epochs),total=epochs,unit='epoch'):
            dw = 0
            db = 0
            for x,y in zip(X,Y):
                dw += self.grad_w(x,y)
                db += self.grad_b(x,y)
                
            self.w -= eta*dw
            self.b -= eta*db

## Fit for toy data

In [18]:
X = np.asarray([[2.5,2.5],[4,-1],[1,-4],[3,1.25],[2,4],[1,5]])
Y = [1,1,1,0,0,0]

In [19]:
sn = sigmoidNeuron()
sn.fit(X,Y,5,0.25,True)

In [22]:
for i in range(20):
    print(sn.w,sn.b)
    sn.fit(X,Y,5,0.25,True)

[[ 1.32957487 -1.1209001 ]] [-0.02470367]
[[-1.47338104 -1.08811046]] [0.10973069]
[[ 1.3984143  -0.08009306]] [0.16894371]
[[ 0.11203715 -1.28889196]] [-0.01931484]
[[-0.75591489  3.09824233]] [-0.02082363]
[[ 1.93869225 -1.4454309 ]] [0.02499081]
[[-1.11156593 -0.6006637 ]] [-0.16780639]
[[ 0.82443545 -1.06891553]] [-0.03011193]
[[-1.33278886  0.82039395]] [-0.05137805]
[[-1.3017386  -1.04587495]] [0.10058837]
[[1.16833171 1.39153366]] [0.07592615]
[[-1.00697408 -0.98610251]] [0.03732856]
[[-0.01411591 -1.86915231]] [0.10244195]
[[4.46239269 0.28599535]] [0.06846715]
[[ 0.34069228 -1.35305261]] [-0.10067644]
[[1.53119314 1.49944014]] [0.01435968]
[[0.84470138 0.30974153]] [0.24393047]
[[-0.92028808 -0.96205005]] [-0.02038906]
[[-1.2690171   1.81059952]] [0.04161546]
[[-0.25979278 -1.07032709]] [-0.05174688]
